/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProspectsRouteImport } from './routes/_app/prospects'
import { Route as AppReleasesRouteImport } from './routes/_app/releases'
import { Route as AppRequestsRouteImport } from './routes/_app/requests'
import { Route as AppSitesRouteImport } from './routes/_app/sites'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as AppCustomersOrgIdRouteImport } from './routes/_app/customers/$orgId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProspectsRoute = AppProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => AppRoute,
} as any)
const AppReleasesRoute = AppReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesRoute = AppSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersOrgIdRoute = AppCustomersOrgIdRouteImport.update({
  id: '/customers/$orgId',
  path: '/customers/$orgId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/prospects': typeof AppProspectsRoute
  '/releases': typeof AppReleasesRoute
  '/requests': typeof AppRequestsRoute
  '/sites': typeof AppSitesRoute
  '/customers/$orgId': typeof AppCustomersOrgIdRoute
  '/customers/': typeof AppCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/prospects': typeof AppProspectsRoute
  '/releases': typeof AppReleasesRoute
  '/requests': typeof AppRequestsRoute
  '/sites': typeof AppSitesRoute
  '/': typeof AppIndexRoute
  '/customers/$orgId': typeof AppCustomersOrgIdRoute
  '/customers': typeof AppCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/prospects': typeof AppProspectsRoute
  '/_app/releases': typeof AppReleasesRoute
  '/_app/requests': typeof AppRequestsRoute
  '/_app/sites': typeof AppSitesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/customers/$orgId': typeof AppCustomersOrgIdRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/prospects'
    | '/releases'
    | '/requests'
    | '/sites'
    | '/customers/$orgId'
    | '/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/prospects'
    | '/releases'
    | '/requests'
    | '/sites'
    | '/'
    | '/customers/$orgId'
    | '/customers'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/prospects'
    | '/_app/releases'
    | '/_app/requests'
    | '/_app/sites'
    | '/_app/'
    | '/_app/customers/$orgId'
    | '/_app/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospects': {
      id: '/_app/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof AppProspectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/releases': {
      id: '/_app/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof AppReleasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests': {
      id: '/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sites': {
      id: '/_app/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AppSitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$orgId': {
      id: '/_app/customers/$orgId'
      path: '/customers/$orgId'
      fullPath: '/customers/$orgId'
      preLoaderRoute: typeof AppCustomersOrgIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProspectsRoute: typeof AppProspectsRoute
  AppReleasesRoute: typeof AppReleasesRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSitesRoute: typeof AppSitesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersOrgIdRoute: typeof AppCustomersOrgIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProspectsRoute: AppProspectsRoute,
  AppReleasesRoute: AppReleasesRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSitesRoute: AppSitesRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersOrgIdRoute: AppCustomersOrgIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
